import React, { useState } from "react";
import Modal from "react-bootstrap/Modal";
import Button from "react-bootstrap/Button";
import Col from "react-bootstrap/Col";
import Form from "react-bootstrap/Form";
import Row from "react-bootstrap/Row";
import jsPDF from "jspdf";
import { storage } from "../Firebase/firebase";
import { ref, uploadBytes, getDownloadURL } from "firebase/storage";
import { v4 } from "uuid";

function UpdateStaff({ closeModal, details }) {
  const id = details;
  const name = localStorage.getItem("userName");
  const [medicine, setMedicine] = useState([]);
  const [newMedicine, setNewMedicine] = useState("");
  const [upload, setUpload] = useState(false);
  const [reportURL, setReportURL] = useState("");
  const [validated, setValidated] = useState(false);
  const [imageUpload, setImageUpload] = useState(null);
  const [uploaded, setUploaded] = useState(false);

  function generatePrescription(event) {
    event.preventDefault();

    if (medicine.length === 0) {
      alert("No details were added");
    } else {
      generateLink();
      setUpload(true);
    }

    function generateLink() {
      const doc = new jsPDF("potrait", "px", [200, 300], "false");
      doc.text(10, 30, "Prescription ID : " + id);
      doc.text(10, 50, "Generated By Dr. " + name);
      medicine.map((med, index) => {
        doc.text(30, 60 + (index + 1) * 30, med);
      });
      doc.save("prescription.pdf");
      setUpload(true);
    }
  }

  const handleSubmit = (event) => {
    const form = event.currentTarget;
    if (form.checkValidity() === false) {
      event.preventDefault();
      event.stopPropagation();
    }

    setValidated(true);
  };

  async function uploadImage(event) {
    handleSubmit(event);
    event.preventDefault();

    // if (imageUpload == null) return alert("Please upload medical report");

    const imageRef = ref(storage, `prescriptions/${imageUpload.name + v4()}`);
    await uploadBytes(imageRef, imageUpload).then((snapshot) => {
      getDownloadURL(snapshot.ref).then((url) => {
        setReportURL(url);
        setUploaded(true);
      });
    });
  }

  async function updateDetails(event) {
    handleSubmit(event);
    event.preventDefault();

    const response = await fetch(`http://localhost:8070/report/update/${id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        id,
        reportURL,
      }),
    });

    const data = await response.json();

    if (data.status === "Prescription added") {
      alert("Prescription added");
      closeModal(false);
      window.location.reload(false);
    } else {
      alert("Try Again");
    }
    setValidated(false);
  }

  return (
    <>
      <Modal show onHide={() => closeModal(false)}>
        <Modal.Header closeButton>
          <h3>Add Prescription</h3>
        </Modal.Header>
        <Modal.Body>
          <div>
            {upload === false && (
              <Form noValidate onSubmit={generatePrescription}>
                <Row className="mb-3">
                  <Form.Group as={Col} md="12" controlId="id">
                    <Form.Label>Report ID</Form.Label>
                    <Form.Control disabled placeholder={id} />
                  </Form.Group>
                  <Form.Group as={Col} md="12" controlId="specialization">
                    <Form.Label>Medicine</Form.Label>
                    <Form.Control
                      type="text"
                      minLength={3}
                      aria-describedby="inputGroupPrepend"
                      onChange={(event) => setNewMedicine(event.target.value)}
                    />
                    <Button
                      onClick={() => {
                        if (newMedicine.length === 0) {
                        } else {
                          setMedicine([...medicine, newMedicine]);
                        }
                      }}
                    >
                      Add To List
                    </Button>
                  </Form.Group>
                  <Form.Group as={Col} md="12" controlId="email">
                    <Form.Label>Medicine List</Form.Label>
                    <textarea
                      required
                      class="form-control"
                      disabled
                      type="text"
                      value={medicine}
                    />
                    <Button
                      className="btn-danger"
                      onClick={() => {
                        setMedicine([]);
                      }}
                    >
                      Clear List
                    </Button>
                  </Form.Group>
                </Row>
                <Button type="submit">Generate Prescription</Button>
              </Form>
            )}
            {upload === true && uploaded === false && (
              <Form noValidate validated={validated} onSubmit={uploadImage}>
                <Row className="mb-3">
                  <Form.Group as={Col} md="12" controlId="url">
                    <Form.Label>Upload prescription</Form.Label>
                    <Form.Control
                      required
                      type="file"
                      onChange={(event) => {
                        setImageUpload(event.target.files[0]);
                      }}
                    />
                    <Form.Control.Feedback
                      type="invalid"
                      isInvalid={imageUpload == null}
                    >
                      {imageUpload == null && "Image is required"}
                    </Form.Control.Feedback>
                    <Form.Control.Feedback></Form.Control.Feedback>
                  </Form.Group>
                </Row>
                <Button type="submit">Upload</Button>
              </Form>
            )}
            {uploaded === true && (
              <Form noValidate validated={validated} onSubmit={updateDetails}>
                <Row className="mb-3">
                  <Form.Group as={Col} md="12" controlId="url">
                    <Form.Label>Upload prescription</Form.Label>
                    <Form.Control
                      disabled
                      required
                      type="text"
                      placeholder={imageUpload.name}
                    />
                  </Form.Group>
                </Row>
                <Button type="submit">Add Prescription</Button>
              </Form>
            )}
          </div>
        </Modal.Body>
      </Modal>
    </>
  );
}

export default UpdateStaff;
